### ISSUE TITLE
Feature request: Add PSU control

### ISSUE THREAD

**Issue by upya4ko** [Maxinger15/connectandprint#5]
Hi, thanks for your work, this plugin can help start printer in one click in slicer, but in my case i use [OctoPrint PSU Control](https://github.com/kantlivelong/OctoPrint-PSUControl) and [Physical Button](https://github.com/LuxuSam/PhysicalButton) plugins to power ON printer PSU before print.

Can please you add support of option "Toggle PSU before print", it may be as GPIO command like 
```raspi-gpio set <GPIO> [options]``` 
or use *OctoPrint PSU Control* API call 
```
curl -s -H "Content-Type: application/json" -H "X-Api-Key: API_KEY" -X POST -d '{ "command":"turnPSUOn" }' http://127.0.0.1/api/plugin/psucontrol
```

to detect PSU status i check GPIO pin status ```/bin/sh -c "if [ $(gpio read 7) -eq 0 ] ; then exit 1; else exit 0; fi"``` so no need toggle if printer is already ON.

I think this functions can make plugin more popular.

**Comment by Maxinger15** [comment]
Hi @upya4ko,
I have created a version with support for PSU-Control.
If it detects that PSU-Control is installed it registers as a plugin for that and tells PSU-Control to power on your PSU
if you upload+print a file.
Since I don´t have PSU-Control set up can you test the code?
To do so you have to uninstall the connectandprint plugin in the octoprint pluginmanager, got to the search plugin page and
use the "From url" feature.
The url is `https://raw.githubusercontent.com/Maxinger15/connectandprint/add-psu-control/connectandprint.py`
After a restart it should work as expected.

**Comment by upya4ko** [comment]
> https://raw.githubusercontent.com/Maxinger15/connectandprint/add-psu-control/connectandprint.py


Sorry for delay, have long print...

Confirm, PSUcontrol plugin work in first time, now test twice, continue testing.
Thank you very much for feature!

**Comment by Maxinger15** [comment]
Thats great 😃 
I will let you test some more and merge the changes into master next week if I don´t hear something from you.

**Comment by upya4ko** [comment]
> Thats great smiley I will let you test some more and merge the changes into master next week if I don´t hear something from you.

OK, today test again twice, all work as needed, continue testing, if found bugs i report here.

**Comment by upya4ko** [comment]
@Maxinger15 Hi, testing going OK, after update octoprint plugin re-downloaded from main so i back this branch version and all work OK again, plugin used every day, no bugs founded.

**Comment by Maxinger15** [comment]
Thank you.
I merged it into the master branch.
